### PR TITLE
🎶 Soundcloud-App

### PR DESCRIPTION
**Pull request by arturmaiz**

### CODE REVIEW

**Comment by darkRaspberry** [comment]
Thanks for PULL request just make sure your app is not in root folder and is in a separate folder named as your app.

**Comment by arturmaiz** [comment]
Hi,
I created new folder with my project name, it is not in root.

**Comment by darkRaspberry** [comment]
Your Project is so cool. Its nice to work with you.

**Comment by darkRaspberry** [comment]
@arturmaiz  Hi your APP has a **1 minimist vulnerability found in Soundcloud-App/yarn.lock**.
That's not good. I'm trying to provide a fix to patch it. I have merged your PR and request you to make sure your app is free from vulnerability.
In case you are thinking what is matter look at this ss.

Screenshot from 2020-10-10 14-52-46

**Comment by darkRaspberry** [comment]
If you have any fix then PR it.

**Pull request merged**
