### PR TITLE
Pdf extractor

### PR DESCRIPTION
**Pull request by kellydosocorro**
This project transforms the contents of a pdf, into a text file.

### All Submissions:

- [ ] Are you a first time contributor.
- [x] Have you followed the guidelines in our Contributing instructions listed in README.md?

### New PR Submissions:

 - [x] Is your code contain big app. (if Yes,then)
   - [ ] Run audit and see any issue, and try to fix it.
 - [ ] Do your project contain any syslink?.
 - [x] Your PR is not directly in root. (i.e. it is in folder named according to your app.)

### CODE REVIEW

**Comment by darkRaspberry** [comment]
Hey @kellydosocorro can u provide audit report! If u can provide it so easy to merge
Big apps are hard to scan. And may contain small issue.

**Comment by darkRaspberry** [comment]
Moving towards merge!

**Review by darkRaspberry — APPROVED** [review]

**Comment by darkRaspberry** [comment]
Add more PR and mention me for quick merge

**Comment by kellydosocorro** [comment]
I'm sorry, I misunderstood, my application is not so big that it needs an audit report, it has only one file, the others all belong to libs installed on virtualenv. Sorry for the misunderstood and thank you for the opportunity.

**Comment by darkRaspberry** [comment]
@kellydosocorro Its ok. i audited at low level and things didn't bothered me

**Pull request merged**
