### PR TITLE
Changed contributors-list.md, added buttons.css

### PR DESCRIPTION
**Pull request by BOHEUS**

### CODE REVIEW

**Comment by BOHEUS** [comment]
I'm sorry if I did something incorrectly, it's my first time doing this challenge and I'm pretty new to this.

**Comment by darkRaspberry** [comment]
@BOHEUS Its good. But can you make a correction?
Just place your file in a folder as "CCS".
meaning your button.css should be in a folder.
and leave the contributing lists as it is

**Comment by BOHEUS** [comment]
Well, I did this on my local repository so now I have to upload it to GitHub and merge it again, right?

**Comment by darkRaspberry** [comment]
> Well, I did this on my local repository so now I have to upload it to GitHub and merge it again, right?

YUP

**Comment by BOHEUS** [comment]
Ok, give me a moment. Also I'll do another 3 pull requests with css stuff.

**Comment by darkRaspberry** [comment]
> Ok, give me a moment. Also I'll do another 3 pull requests with css stuff.

Update a file. then create a PR.
then update new file and create a PR ok>

**Comment by BOHEUS** [comment]
Ok, I understand

**Comment by BOHEUS** [comment]
I think I fixed this, can you check it?

**Comment by darkRaspberry** [comment]
@BOHEUS This seems really nice. Thanks for this PR. I will be merged.
Ask your friends to do PR or do the same.

**Comment by BOHEUS** [comment]
Ok, I'll tell them about this very soon.

**Pull request merged**
